name: Test Command Failure
on:
  push:

jobs:
  print:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          mkdir foo
          pushd foo
          echo 1
          (exit 255) >> foo.txt
          echo 2
          popd
